---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-hnts-dp
  labels:
    ingress: py-hnts-dp
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: py-hnts-dp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: py-hnts-dp
    spec:
      containers:
        - name: py-hnts
          image: public.ecr.aws/z7s0e9e6/py-hnts
          imagePullPolicy: "Always"
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 8081
              name: py-hnts-exp
            - containerPort: 8080
              name: py-hnts

---
apiVersion: v1
kind: Service
metadata:
 name: py-hnts-svc
spec:
 type: ClusterIP
 selector:
   app.kubernetes.io/name: py-hnts-dp
 ports:
 - port: 80
   targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: py-hnts
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: py-hnts.internal
    http:
      paths:
      - path: /
        pathType: Prefix 
        backend:
          service:
            name: py-hnts-svc
            port:
              number: 80
